#!/usr/bin/env python3
import rclpy #ROS2 library for python
from rclpy.node import Node #Import node class with functionalities


class MyNode(Node): #Allows class to use all functionalities from "Node"

    def __init__(self): #Creating constructor
        super().__init__("py_test") #Parent constructoe to initialize the node from the node class
        self.get_logger().info("Hello world")

def main(args=None):
    rclpy.init(args=args) #Initialize ROS2 communications to use nodes
    node = Node("py_test") #Creating node with class "Node" and name "py_test" . NB! Node is inside the python file!
    node.get_logger().info("Hello world") #Test print
    rclpy.spin(node) #Keep the node alive
    rclpy.shutdown()

if __name__ == "__main__":
    main() #Needed to run the program directly from the terminal (call the main function automatically)
